INSERT INTO TB_USUARIO(USU_ID_USUARIO,USU_DS_EMAIL,USU_DS_NOME,USU_NR_IDADE,USU_DS_SENHA,USU_FL_ATIVO) VALUES (sq_tbl_usuario.nextval,'teste@gmail.com', 'Teste', 87, '$2a$10$rdAvFJY5KHHeiNr0549IL.UnmpdxVp2L6gb.V0Ua22qr6/BGaPw6e',1);

INSERT INTO TB_VEICULO(VEI_ID_VEICULO, VEI_DS_MARCA, VEI_DS_MODELO, VEI_TP_COMBUSTIVEL, VEI_NR_CONSUMO, FK_USUARIO) VALUES (sq_tbl_veiculo.nextval, 'Honda', 'Civic', 'GASOLINA', 20.1, 1);
INSERT INTO TB_VEICULO(VEI_ID_VEICULO, VEI_DS_MARCA, VEI_DS_MODELO, VEI_TP_COMBUSTIVEL, VEI_NR_CONSUMO, FK_USUARIO) VALUES (sq_tbl_veiculo.nextval, 'Toyota', 'Etios', 'ETANOL', 26.0, 1);

INSERT INTO TB_POSTO(PT_ID_POSTO, PT_DS_NOME, PT_LT_POSTO, PT_LG_POSTO, PT_NR_AVALIACAO, PT_PR_GASOLINA, PT_PR_ETANOL, PT_PR_DIESEL,PT_PR_GAS) VALUES (sq_tbl_posto.nextval, 'Shell','-1234.21', '-11235.64', 5, 5.1, 5.4, 5.8, 5.6);

INSERT INTO TB_VIAGEM(VIA_ID_VIAGEM, VIA_LT_ORIGEM, VIA_LG_ORIGEM, VIA_LT_DESTINO, VIA_LG_DESTINO, VIA_NR_DISTANCIA, VIA_TP_DURACAO, FK_VEICULO, FK_POSTO) VALUES (sq_tbl_viagem.nextval, '-1234.21', '-11235.64', '-11235.64','-11235.64', 56.0, 15 , 1, 1);

INSERT INTO TB_PERFIL(PF_ID_PERFIL, PF_NM_PERFIL) VALUES (sq_tbl_perfil.nextval, 'ADM');
INSERT INTO TB_PERFIL(PF_ID_PERFIL, PF_NM_PERFIL) VALUES (sq_tbl_perfil.nextval, 'USUARIO');

INSERT INTO TB_USUARIO_PERFIL(FK_USUARIO,FK_PERFIL) VALUES (1,1);